#!/bin/bash
# 
# created by: PtrckM
# docker build instance run script
# usage: wget https://raw.githubusercontent.com/PtrckM/hummingbot-support/master/run
#        chmod a+x run
#        ./run
#

if [[ -z "$@" ]]; then
   echo -ne "\n[] -- listing instance names...\n\n"
   docker ps -a | awk '{print $NF}'
   echo -ne "\n[] -- Usage: ./run instance_name\n"
   echo -ne "[] -- No instance name entered, exiting...\n\n"
   exit 1
else
   echo -ne "\n[] -- starting instance and attaching to it... >> "
   docker start $@ && docker attach $@
   exit 1
fi



