#!/bin/bash

# Video compress for screen recording
# this script will compress your video into a small bytes.
# created by: Patrick
#
# Requirements: installed conda
# Tested on: macos (intel/m1), linux (ubuntu 20.04)
# Dependency: ffmpeg
#        for mac: brew install ffmpeg
#        for ubuntu: sudo apt install ffmpeg
# usage: wget https://raw.githubusercontent.com/PtrckM/hummingbot-support/master/videomizer
#        chmod +x videomizer
#        ./videomizer urvideo.mov
#

if [[ -z "$@" ]]; then
        echo ""
        echo "Videomizer - compress video screen recording"
        echo "enter filename (or with path): ./videomize thisvideo.mov"
        echo ""
        exit 1
else
        echo ""
        ffmpeg -i $@ videomize.mp4 -nostats -loglevel 0
                mv videomize.mp4 $@_videomize.mp4
                ls -lah $@ $@_videomize.mp4
                echo ""
                exit 1
fi
